name: tests
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
# TODO: wait until build only test
jobs:
  test-rmf:
    name: Run senarios of rmf
    runs-on: ubuntu-latest
    container:
      image: docker.pkg.github.com/tanyouliang95/rmf/rmf_demos:latest
      credentials:
        username: ${{ github.repository_owner }}
        password: ${{ secrets.GITHUB_TOKEN }}
    steps:
    - name: checkout
      uses: actions/checkout@v2
      with:
        path: rmf/
    - name: run-tests
      shell: bash
      run: |
        source /ros_entrypoint.sh
        echo "ec: Run Test "
        python3 rmf/tests/integration_test.py
        echo "ec: End "
